---
# tasks file to start turnserver container

- name: "{{ 'Create' if (state is undefined or 'absent' not in state) else 'Terminate' }} the turnserver container"
  docker_container:
    name:           'turn_server'
    image:          "coturn/coturn:{{ docker_turnserver_image | default('latest') }}"
    restart_policy: 'unless-stopped'
    command: >
      -n
      --log-file=stdout
      --external-ip=$(detect-external-ip)
      --listening-port=3478
      --no-cli
      --fingerprint
      --use-auth-secret
      --static-auth-secret={{ lookup('password', '{{ nextcloud_credential_store }}/talk_secret chars=ascii_letters,digits length=32') | lower }}
      --realm={{ nextcloud_server_fqdn }}
      --total-quota=100
      --bps-capacity=0
      --stale-nonce
      --no-multicast-peers
      --min-port=49160 
      --max-port=49200
    volumes:
      - 'turnserver-data-vol:/var/lib/coturn:rw'
    ports:
      - 3478:3478/udp
      - 3478:3478/tcp
      - 49152-49200:49152-49200/udp
    state:          '{{ state | default("started") }}'
