---
# Ubuntu related OS tasks

- name: apt dist-upgrade
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 3600
    autoremove: true

- name: install additional packages
  apt:
    name:
      - zip
      - unzip
      - bzip2
      - screen
      - curl
      - cron
      - language-pack-en-base
      - software-properties-common
      - facter
      - unattended-upgrades
      - gnupg2
      - python3-passlib
      - python3-bcrypt
    state: latest
